# Generated by Django 5.1.2 on 2024-10-24 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalBacked', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='registro',
            field=models.CharField(default=None, max_length=20, verbose_name='registro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalBacked.medico'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
