# Generated by Django 5.1.2 on 2024-10-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalBacked', '0003_alter_usuario_apellido_alter_usuario_celular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='especilidad',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='medico',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medico',
            name='registro',
            field=models.CharField(max_length=20),
        ),
    ]
