# Generated by Django 5.1.2 on 2024-10-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalBacked', '0004_alter_medico_especilidad_alter_medico_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=256),
        ),
    ]
