# Generated by Django 5.1.2 on 2024-10-25 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalBacked', '0005_alter_usuario_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medico',
            old_name='especilidad',
            new_name='especialidad',
        ),
    ]
